# autogenerated by txs
#include:ifpdf
#include:ifxetex
#include:kvoptions
#include:pdfescape
\AccSuppSetup#S
\ActualTextDriverDefault#S
\BeginAccSupp{arg1}#S
\EndAccSupp{arg1}#S
\x#S
accsupp-pdftex.def#S
accsupp.cfg#S
ifpdf.sty#S
ifxetex.sty#S
pdfescape.sty#S
