# autogenerated by txs
#include:amssymb
#include:tikz
#include:xkeyval
\background#S
\begin{boite}#S
\boxcolor#S
\couleurs{arg1}#S
\end{boite}#S
\newboxedtheorem{arg1}{arg2}{arg3}{arg4}#S
\size#S
\thcounter#S
\titlebackground#S
\titleboxcolor#S
\titlecolor#S
\titre#S
