# autogenerated by txs
#include:iftex
\NeedsETeX{arg1}#S
\RequireAlephTeX#S
\RequireLuaHBTeX#S
\RequireLuaTeX#S
\RequirePDFTeX#S
\RequireTUTeX#S
\RequireVTeX#S
\RequireXeTeX#S
\RequireeTeX#S
\RequirepTeX#S
\RequirepTeXng#S
\RequireupTeX#S
\csname#S
\pdffalse#S
\pdftrue#S
\\NeedsETeX#S
